### ISSUE TITLE
Inconsistent input parameters

### ISSUE THREAD

**Issue by RupertBarrow** [cumulus-actions/release-beta-2gp#1]
The example Github Action [standard-workflows](https://github.com/cumulus-actions/standard-workflows)/[.github](https://github.com/cumulus-actions/standard-workflows/tree/main/.github)/[workflows](https://github.com/cumulus-actions/standard-workflows/tree/main/.github/workflows)/beta-2gp.yml passes the parameter `packaging-org-auth-url ` to this action `cumulus-actions/release-beta-2gp`, whereas this action expects the usual `dev-hub-auth-url ` input parameter

**Comment by davidmreed** [comment]
This has been fixed - apologies!
